/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MisionFamiliasRouteImport } from './routes/mision-familias'
import { Route as MisionDocentesRouteImport } from './routes/mision-docentes'
import { Route as MisionAdultosRouteImport } from './routes/mision-adultos'
import { Route as MisionAdolescentesRouteImport } from './routes/mision-adolescentes'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as IndexRouteImport } from './routes/index'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionFamiliasRoute = MisionFamiliasRouteImport.update({
  id: '/mision-familias',
  path: '/mision-familias',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionDocentesRoute = MisionDocentesRouteImport.update({
  id: '/mision-docentes',
  path: '/mision-docentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionAdultosRoute = MisionAdultosRouteImport.update({
  id: '/mision-adultos',
  path: '/mision-adultos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionAdolescentesRoute = MisionAdolescentesRouteImport.update({
  id: '/mision-adolescentes',
  path: '/mision-adolescentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidad': typeof ComunidadRoute
  '/mision-adolescentes': typeof MisionAdolescentesRoute
  '/mision-adultos': typeof MisionAdultosRoute
  '/mision-docentes': typeof MisionDocentesRoute
  '/mision-familias': typeof MisionFamiliasRoute
  '/nosotros': typeof NosotrosRoute
  '/plataforma': typeof PlataformaRoute
  '/privacidad': typeof PrivacidadRoute
  '/recursos': typeof RecursosRoute
  '/terminos': typeof TerminosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidad': typeof ComunidadRoute
  '/mision-adolescentes': typeof MisionAdolescentesRoute
  '/mision-adultos': typeof MisionAdultosRoute
  '/mision-docentes': typeof MisionDocentesRoute
  '/mision-familias': typeof MisionFamiliasRoute
  '/nosotros': typeof NosotrosRoute
  '/plataforma': typeof PlataformaRoute
  '/privacidad': typeof PrivacidadRoute
  '/recursos': typeof RecursosRoute
  '/terminos': typeof TerminosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidad': typeof ComunidadRoute
  '/mision-adolescentes': typeof MisionAdolescentesRoute
  '/mision-adultos': typeof MisionAdultosRoute
  '/mision-docentes': typeof MisionDocentesRoute
  '/mision-familias': typeof MisionFamiliasRoute
  '/nosotros': typeof NosotrosRoute
  '/plataforma': typeof PlataformaRoute
  '/privacidad': typeof PrivacidadRoute
  '/recursos': typeof RecursosRoute
  '/terminos': typeof TerminosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidad'
    | '/mision-adolescentes'
    | '/mision-adultos'
    | '/mision-docentes'
    | '/mision-familias'
    | '/nosotros'
    | '/plataforma'
    | '/privacidad'
    | '/recursos'
    | '/terminos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidad'
    | '/mision-adolescentes'
    | '/mision-adultos'
    | '/mision-docentes'
    | '/mision-familias'
    | '/nosotros'
    | '/plataforma'
    | '/privacidad'
    | '/recursos'
    | '/terminos'
  id:
    | '__root__'
    | '/'
    | '/comunidad'
    | '/mision-adolescentes'
    | '/mision-adultos'
    | '/mision-docentes'
    | '/mision-familias'
    | '/nosotros'
    | '/plataforma'
    | '/privacidad'
    | '/recursos'
    | '/terminos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadRoute: typeof ComunidadRoute
  MisionAdolescentesRoute: typeof MisionAdolescentesRoute
  MisionAdultosRoute: typeof MisionAdultosRoute
  MisionDocentesRoute: typeof MisionDocentesRoute
  MisionFamiliasRoute: typeof MisionFamiliasRoute
  NosotrosRoute: typeof NosotrosRoute
  PlataformaRoute: typeof PlataformaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecursosRoute: typeof RecursosRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision-familias': {
      id: '/mision-familias'
      path: '/mision-familias'
      fullPath: '/mision-familias'
      preLoaderRoute: typeof MisionFamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision-docentes': {
      id: '/mision-docentes'
      path: '/mision-docentes'
      fullPath: '/mision-docentes'
      preLoaderRoute: typeof MisionDocentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision-adultos': {
      id: '/mision-adultos'
      path: '/mision-adultos'
      fullPath: '/mision-adultos'
      preLoaderRoute: typeof MisionAdultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision-adolescentes': {
      id: '/mision-adolescentes'
      path: '/mision-adolescentes'
      fullPath: '/mision-adolescentes'
      preLoaderRoute: typeof MisionAdolescentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadRoute: ComunidadRoute,
  MisionAdolescentesRoute: MisionAdolescentesRoute,
  MisionAdultosRoute: MisionAdultosRoute,
  MisionDocentesRoute: MisionDocentesRoute,
  MisionFamiliasRoute: MisionFamiliasRoute,
  NosotrosRoute: NosotrosRoute,
  PlataformaRoute: PlataformaRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecursosRoute: RecursosRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
